

var modules_obj = {
	"desk":{
			id: 'desk',
			url: '/module/desk/desk.html',
			params:["module",'title']
	},
	"login":{
		id:"login",
		url:"/module/login/login.html"
		
		},
	"appcenter":{
		id:"appcenter",
		url:"/module/appcenter/appcenter.html",
		params:["id","name"]
		
	},
	"headimg":{
		id:"headimg",
		url:"/module/personal-center/personal.html"
	},
	"person-quit":{
		id:"person-quit",
		url:"/module/login/login.html"
	},
	"personal-details":{
		id:"personal-details",
		url:"/module/personal-center/personal-details.html"
	},
	"report":{
		id:"report",
		url:"/module/personal-center/report.html"
	},
	"my-commforstudent":{
		id:"my-commforstudent",
		url:"/module/my-class/my-commforstudent/my-commforstudent.html"
	},
	"my-teacher":{
		id:"my-teacher",
		url:"/module/my-class/my-teacher/my-teacher.html"
	},
	"teacher-details":{
		id:"teacher-details",
		url:"/module/my-class/my-teacher/teacher-details.html",
		params:["id"]
	},
	"my-studentcourse":{
		id:"my-studentcourse",
		url:"/module/my-class/my-studentcourse/my-studentcourse.html",
		params:["id"]
	},
	"my-studentclass":{
		id:"my-studentclass",
		url:"/module/my-class/my-studentclass/pullrefresh_main.html"
	},
	
	"student-details":{
		id:"student-details",
		url:"/module/my-class/my-studentclass/student-details.html",
		params:["id"]
	},
	"studentbbs":{
		id:"studentbbs",
		url:"/module/school-center/studentbbs/studentbbs.html"
	},
	"my-bbs":{
		id:"my-bbs",
		url:"/module/school-center/studentbbs/my-bbs/pullrefresh_main.html"
	},
	"my-bbs-details":{
		id:"my-bbs-details",
		url:"/module/school-center/studentbbs/my-bbs/my-bbs-details.html",
		params:["id"]
	},
	"add-bbs":{
		id:"add-bbs",
		url:"/module/school-center/studentbbs/my-bbs/add-bbs.html",
		params:["id"]
	},
	"all-bk":{
		id:"all-bk",
		url:"/module/school-center/studentbbs/all-bk/all-bk.html"
	},
	"all-bbs":{
		id:"all-bbs",
		url:"/module/school-center/studentbbs/all-bbs/pullrefresh_main.html"
	},
	"bk-bbs":{
		id:"bk-bbs",
		url:"/module/school-center/studentbbs/all-bk/pullrefresh_main.html",
		params:["id","title"]
	},
	"my-activitystudent":{
		id:"my-activitystudent",
		url:"/module/school-center/my-activitystudent/pullrefresh_main.html"
	},
	"activity-types":{
		id:"activity-types",
		url:"/module/school-center/my-activitystudent/types/pullrefresh_main.html",
		params:["id","name"]
	},
	"activity-details":{
		id:"activity-details",
		url:"/module/school-center/my-activitystudent/activity-details.html",
		params:["id"]
	},
	"my-schoolnews":{
		id:"my-schoolnews",
		url:"/module/school-center/my-schoolnews/my-teacher.html"
	},
	"news-rank":{
		id:"news-rank",
		url:"/module/school-center/my-schoolnews/rank/pullrefresh_main.html"
	},
	"news-details":{
		id:"news-details",
		url:"/module/school-center/my-schoolnews/news-details.html",
		params:["id"]
	},
	"my-studentschoolnotice":{
		id:"my-studentschoolnotice",
		url:"/module/school-center/my-studentschoolnotice/pullrefresh_main.html"
	},
	"notice-details":{
		id:"notice-details",
		url:"/module/school-center/my-studentschoolnotice/notice-details.html",
		params:["id"]
	},
	"my-studenthomework":{
		id:"my-studenthomework",
		url:"/module/homework-manage/my-studenthomework/pullrefresh_main.html"
	},
	"homework-details":{
		id:"homework-details",
		url:"/module/homework-manage/my-studenthomework/homework-details.html",
		params:["id"]
	},
	"my-scorerankstudent":{
		id:"my-scorerankstudent",
		url:"/module/exam-center/my-scorerankstudent/pullrefresh_main.html"
	},
	"my-studentbjks":{
		id:"my-studentbjks",
		url:"/module/exam-center/my-studentbjks/pullrefresh_main.html"
	},
	"scorebj-details":{
		id:"scorebj-details",
		url:"/module/exam-center/my-studentbjks/scorebj/pullrefresh_main.html",
		params:["id","name"]
	},
	"my-practiseHistoryscore":{
		id:"my-practiseHistoryscore",
		url:"/module/exam-center/my-historyscorebjks/historybjks.html"
	},
	"my-studentnjks":{
		id:"my-studentnjks",
		url:"/module/exam-center/my-studentnjks/pullrefresh_main.html"
	},
	"scorenj-details":{
		id:"scorenj-details",
		url:"/module/exam-center/my-studentnjks/scorenj/pullrefresh_main.html",
		params:["id","name"]
	},
	"my-historyscore":{
		id:"my-historyscore",
		url:"/module/exam-center/my-historyscorenjks/historynjks.html"
	},
//	老师端
	"my-note":{
		id:"my-note",
		url:"/module/oa/my-note/pullrefresh_main.html"
		
	},
	"my-note-add":{
		id:"my-note-add",
		url:"/module/oa/my-note/add.html",
		params:["id"]
	},
	"my-school":{
		id:"my-school",
		url:"/module/school-manage/school-details/school-details.html"
	},
	"my-course":{
		id:"my-course",
		url:"/module/school-manage/my-course/my-course.html"
	},
	"my-teacherschoolnotice":{
		id:"my-teacherschoolnotice",
		url:"/module/teacher-school-center/my-schoolnotice/pullrefresh_main.html"
	},
	"notice-details":{
		id:"notice-details",
		url:"/module/teacher-school-center/my-schoolnotice/notice-details.html",
		params:["id"]
	},
	"my-notice":{
		id:"my-notice",
		url:"/module/teacher-school-center/notice-manage/pullrefresh_main.html"
	},
	"my-notice-add":{
		id:"my-notice-add",
		url:"/module/teacher-school-center/notice-manage/my-notice-add.html"
	}
}
